### ISSUE TITLE
[WIP] Fix issues with LSL syntax for Sublime Text 3

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#5]
* [x] Add [syntax_tests](https://www.sublimetext.com/docs/3/syntax.html#testing) for LSL.
* [x] Redo `*.sublime-syntax` file.
    ``` YAML
    # http://www.sublimetext.com/docs/3/syntax.html

     - match: some-regex
       push: target-scope
       with_prototype:
         - match: some-regex # or include
           scope: target-scope
         - match: some-regex # look ahead
           pop: true
    ```
  * [x] new syntax file must pass the syntax tests
    * <http://www.sublimetext.com/docs/3/syntax.html#testing>
  * [x] check possibility of included and escaped languages within strings using the new `embed` action (Build 3153+)
    * JSON
    * HTML
* [ ] prevent user functions within other scopes
* [ ] fix conditional blocks following `keyword.control.conditional`
* [ ] scope `punctuation.accessor` and elements following:
  * vectors
  * rotations
